# Generated by Django 5.1.1 on 2024-11-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_box_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Box',
        ),
    ]
