# Generated by Django 5.1.2 on 2024-11-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='store',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='store',
            name='logo',
        ),
        migrations.AddField(
            model_name='store',
            name='background_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
