# Generated by Django 5.1.2 on 2024-11-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('seller', 'Vendedor'), ('buyer', 'Comprador')], max_length=10),
        ),
    ]
