# Generated by Django 5.1.3 on 2024-11-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_cpf_profile_cpf_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cep',
            new_name='CEP',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='complement',
            new_name='complemento',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='endereço',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='telefone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='nascimento',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
