# Generated by Django 5.1.3 on 2024-11-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_cep_profile_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nascimento',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
