# Generated by Django 5.1.3 on 2024-11-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nascimento',
            field=models.DateTimeField(default='2000-01-01'),
        ),
    ]
