# Generated by Django 5.1.3 on 2024-11-25 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_join_date_alter_profile_nascimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_type',
            new_name='tipo_de_usuário',
        ),
    ]
