# Generated by Django 5.1.3 on 2024-11-29 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_payment_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='box',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selected_box', to='users.cartitem'),
        ),
    ]
