# Generated by Django 5.1.3 on 2024-11-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_subscription_payment_alter_subscription_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='store',
        ),
    ]
