# Generated by Django 5.1.3 on 2024-12-01 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_subscription_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_box', to='users.cartitem'),
        ),
    ]
