# Generated by Django 5.1.2 on 2024-11-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='image',
        ),
        migrations.AddField(
            model_name='box',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
